trigger:
- master

pool:
  vmImage: ubuntu-latest

# AGENT VM IMAGE
name: devops-agent-01

stages:
  - stage: TerraformValidate
    jobs:
      - job: Terraform-Validate
        continueOnError: false
        steps:
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)/aks-terraform'
            artifact: 'aks-terraform-artifacts'
            publishLocation: 'pipeline'

          