trigger:
- master

pool:
  vmImage: ubuntu-latest

# AGENT VM IMAGE
name: devops-agent-01

stages:
  - stage: TerraformValidate
    pool:
     name: devops-agent-01
    jobs:
      - job: TerraformValidate
        continueOnError: false
        steps:
        - task: PublishPipelineArtifact@1
          displayName: Publish-Artifact
          inputs:
            targetPath: '$(Pipeline.Workspace)/aks-terraform'
            artifact: 'aks-terraform-artifacts'
            publishLocation: 'pipeline'
        - task: TerraformCLI@2
          displayName: Terraform-init
          inputs:
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/aks-terraform'
            backendType: 'azurerm'
            backendServiceArm: 'azure-rg-connection'
            backendAzureRmSubscriptionId: '410c1a95-68f7-4b30-9fdc-964a1658482d'
            backendAzureRmResourceGroupName: 'DevOps'
            backendAzureRmStorageAccountName: 'devopsdiag621'
            backendAzureRmContainerName: 'aks-tfstatefile'
            backendAzureRmKey: 'terraform-test.tfstate'
            allowTelemetryCollection: true
        - task: TerraformCLI@2
          inputs:
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/aks-terraform'
            allowTelemetryCollection: false
        
      